### ISSUE TITLE
Messaging API - May 2020 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-perl#137]
News: https://developers.line.biz/en/news/2020/05/12/messaging-api-update-may-2020/

- [x] PR #144  Message character limit and media file usage conditions changed 
- [x] PR #145 [Get LINE emoji information from the text object of a webhook event](https://developers.line.biz/en/reference/messaging-api/#wh-text)
- [x] PR #146  [Retry failed message](https://developers.line.biz/en/reference/messaging-api/#retry-api-request)

**Comment by gugod** [comment]
All 3 items are now implement in PRs so they are marked as DONE. This issue can be closed once they are released.

**Comment by gugod** [comment]
All released in 1.18
